source = "https://rubygems.org"
ruby '2.5.1'
gem 'pry'
gem 'google-drive'
gem 'roo'
gem 'watir'
gem 'mechanize'
gem 'nokogiri'
gem 'dotenv'
gem 'twitter'
gem 'rubocop', '~> 0.57.2'
gem 'pry'
gem 'rspec'
gem 'minitest'
gem 'rails'
gem 'list'
gem 'bundler'
